# Generated by Django 4.0.1 on 2022-07-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emails',
            options={'managed': False},
        ),
    ]
